import { Ionicons } from '@expo/vector-icons';
import React, { useState } from 'react';
import { ActivityIndicator, FlatList, KeyboardAvoidingView, Modal, Platform, Pressable, RefreshControl, ScrollView, StyleSheet, Text, TextInput, View, type TextInputProps, type ViewStyle } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useTheme } from '../contexts/ThemeContext';

export function Screen({ children, scroll = true, refreshing, onRefresh, contentStyle }: React.PropsWithChildren<{ scroll?: boolean; refreshing?: boolean; onRefresh?: () => void; contentStyle?: ViewStyle }>) {
  const { colors } = useTheme();
  const content = scroll ? <ScrollView keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false} contentContainerStyle={[s.content, contentStyle]} refreshControl={onRefresh ? <RefreshControl refreshing={!!refreshing} onRefresh={onRefresh} tintColor={colors.primary} /> : undefined}>{children}</ScrollView> : <View style={[s.content, { flex: 1 }, contentStyle]}>{children}</View>;
  return <SafeAreaView edges={['bottom']} style={{ flex: 1, backgroundColor: colors.background }}><KeyboardAvoidingView style={{ flex: 1 }} behavior={Platform.OS === 'ios' ? 'padding' : undefined}>{content}</KeyboardAvoidingView></SafeAreaView>;
}
export function PageHeader({ title, subtitle, action }: { title: string; subtitle?: string; action?: React.ReactNode }) { const { colors } = useTheme(); return <View style={s.header}><View style={{ flex: 1 }}><Text style={[s.title, { color: colors.text }]}>{title}</Text>{subtitle ? <Text style={[s.subtitle, { color: colors.muted }]}>{subtitle}</Text> : null}</View>{action}</View>; }
export function Card({ children, style }: React.PropsWithChildren<{ style?: ViewStyle }>) { const { colors } = useTheme(); return <View style={[s.card, { backgroundColor: colors.surface, borderColor: colors.border }, style]}>{children}</View>; }
export function Button({ title, onPress, icon, variant = 'primary', disabled, loading, compact }: { title: string; onPress: () => void; icon?: keyof typeof Ionicons.glyphMap; variant?: 'primary' | 'outline' | 'danger' | 'soft'; disabled?: boolean; loading?: boolean; compact?: boolean }) { const { colors } = useTheme(); const solid = variant === 'primary'; const danger = variant === 'danger'; const backgroundColor = solid ? colors.primary : danger ? colors.danger : variant === 'soft' ? colors.primarySoft : 'transparent'; const color = solid || danger ? '#fff' : colors.primary; return <Pressable accessibilityRole="button" disabled={disabled || loading} onPress={onPress} style={({ pressed }) => [s.button, compact && s.buttonCompact, { backgroundColor, borderColor: danger ? colors.danger : colors.primary, opacity: disabled ? .45 : pressed ? .8 : 1 }]}>{loading ? <ActivityIndicator size="small" color={color} /> : <>{icon && <Ionicons name={icon} size={18} color={color} />}<Text style={[s.buttonText, { color }]}>{title}</Text></>}</Pressable>; }
export function Field({ label, error, ...props }: TextInputProps & { label: string; error?: string }) { const { colors } = useTheme(); return <View style={s.field}><Text style={[s.label, { color: colors.muted }]}>{label}</Text><TextInput placeholderTextColor={colors.muted} {...props} style={[s.input, { backgroundColor: colors.surface, borderColor: error ? colors.danger : colors.border, color: colors.text }, props.multiline && { minHeight: 90, textAlignVertical: 'top' }, props.style]} />{error ? <Text style={{ color: colors.danger, fontSize: 12, marginTop: 4 }}>{error}</Text> : null}</View>; }
export function SelectField({ label, value, placeholder = 'Select', options, onChange }: { label: string; value?: string; placeholder?: string; options: { label: string; value: string }[]; onChange: (v: string) => void }) { const { colors } = useTheme(); const [open, setOpen] = useState(false); const selected = options.find(x => x.value === value)?.label; return <View style={s.field}><Text style={[s.label, { color: colors.muted }]}>{label}</Text><Pressable onPress={() => setOpen(true)} style={[s.input, s.select, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text numberOfLines={1} style={{ flex: 1, color: selected ? colors.text : colors.muted }}>{selected || placeholder}</Text><Ionicons name="chevron-down" size={18} color={colors.muted} /></Pressable><Modal transparent animationType="slide" visible={open} onRequestClose={() => setOpen(false)}><Pressable onPress={() => setOpen(false)} style={s.modalBackdrop}><Pressable style={[s.sheet, { backgroundColor: colors.surface }]}><View style={[s.sheetHandle, { backgroundColor: colors.border }]} /><Text style={[s.sheetTitle, { color: colors.text }]}>{label}</Text><FlatList data={options} keyExtractor={x => x.value} renderItem={({ item }) => <Pressable onPress={() => { onChange(item.value); setOpen(false); }} style={[s.option, { borderBottomColor: colors.border }]}><Text style={{ color: item.value === value ? colors.primary : colors.text, fontWeight: item.value === value ? '700' : '500' }}>{item.label}</Text>{item.value === value && <Ionicons name="checkmark-circle" size={20} color={colors.primary} />}</Pressable>} /></Pressable></Pressable></Modal></View>; }
export function Segmented({ value, options, onChange }: { value: string; options: { label: string; value: string }[]; onChange: (v: any) => void }) { const { colors } = useTheme(); return <View style={[s.segment, { backgroundColor: colors.surfaceAlt }]}>{options.map(o => <Pressable key={o.value} onPress={() => onChange(o.value)} style={[s.segmentItem, value === o.value && { backgroundColor: colors.surface }]}><Text style={{ color: value === o.value ? colors.primary : colors.muted, fontWeight: '700', fontSize: 13 }}>{o.label}</Text></Pressable>)}</View>; }
export function LoadingView({ fullScreen = false }: { fullScreen?: boolean }) { const { colors } = useTheme(); return <View style={{ flex: fullScreen ? 1 : undefined, minHeight: fullScreen ? undefined : 180, alignItems: 'center', justifyContent: 'center', backgroundColor: fullScreen ? colors.background : undefined }}><ActivityIndicator color={colors.primary} size="large" /></View>; }
export function EmptyState({ icon = 'file-tray-outline', title, text }: { icon?: keyof typeof Ionicons.glyphMap; title: string; text?: string }) { const { colors } = useTheme(); return <View style={s.empty}><Ionicons name={icon} size={42} color={colors.muted} /><Text style={[s.emptyTitle, { color: colors.text }]}>{title}</Text>{text && <Text style={[s.emptyText, { color: colors.muted }]}>{text}</Text>}</View>; }
export function Avatar({ name, size = 44 }: { name: string; size?: number }) { const { colors } = useTheme(); const initials = name.split(' ').filter(Boolean).map(x => x[0]).join('').slice(0, 2).toUpperCase(); return <View style={{ width: size, height: size, borderRadius: size / 2, backgroundColor: colors.primarySoft, alignItems: 'center', justifyContent: 'center' }}><Text style={{ color: colors.primary, fontWeight: '800', fontSize: size * .32 }}>{initials}</Text></View>; }
export function Row({ icon, title, subtitle, onPress, right }: { icon?: keyof typeof Ionicons.glyphMap; title: string; subtitle?: string; onPress?: () => void; right?: React.ReactNode }) { const { colors } = useTheme(); return <Pressable onPress={onPress} disabled={!onPress} style={({ pressed }) => [s.row, { borderBottomColor: colors.border, opacity: pressed ? .65 : 1 }]}>{icon && <View style={[s.rowIcon, { backgroundColor: colors.primarySoft }]}><Ionicons name={icon} size={20} color={colors.primary} /></View>}<View style={{ flex: 1 }}><Text style={[s.rowTitle, { color: colors.text }]}>{title}</Text>{subtitle ? <Text style={[s.rowSub, { color: colors.muted }]}>{subtitle}</Text> : null}</View>{right || (onPress ? <Ionicons name="chevron-forward" size={18} color={colors.muted} /> : null)}</Pressable>; }
export function Pill({ text, tone = 'green' }: { text: string; tone?: 'green' | 'red' | 'blue' | 'amber' | 'gray' }) { const { colors } = useTheme(); const fg = tone === 'red' ? colors.danger : tone === 'blue' ? colors.info : tone === 'amber' ? colors.warning : tone === 'gray' ? colors.muted : colors.primary; return <View style={{ paddingHorizontal: 9, paddingVertical: 4, borderRadius: 20, backgroundColor: `${fg}18` }}><Text style={{ color: fg, fontSize: 11, fontWeight: '800' }}>{text}</Text></View>; }

const s = StyleSheet.create({ content: { padding: 16, paddingBottom: 32, gap: 14 }, header: { flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 2, marginTop: 18 }, title: { fontSize: 24, fontWeight: '800', letterSpacing: -.4 }, subtitle: { fontSize: 13, marginTop: 3 }, card: { borderWidth: 1, borderRadius: 16, padding: 16, shadowColor: '#000', shadowOpacity: .035, shadowRadius: 8, shadowOffset: { width: 0, height: 3 }, elevation: 1 }, button: { minHeight: 48, borderRadius: 12, paddingHorizontal: 16, borderWidth: 1, flexDirection: 'row', gap: 8, alignItems: 'center', justifyContent: 'center' }, buttonCompact: { minHeight: 38, paddingHorizontal: 12 }, buttonText: { fontWeight: '800', fontSize: 14 }, field: { gap: 6 }, label: { fontSize: 12, fontWeight: '700' }, input: { minHeight: 48, borderWidth: 1, borderRadius: 11, paddingHorizontal: 13, fontSize: 15 }, select: { flexDirection: 'row', alignItems: 'center' }, modalBackdrop: { flex: 1, backgroundColor: '#0007', justifyContent: 'flex-end' }, sheet: { maxHeight: '72%', borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: 18 }, sheetHandle: { height: 4, width: 42, alignSelf: 'center', borderRadius: 4, marginBottom: 14 }, sheetTitle: { fontSize: 18, fontWeight: '800', marginBottom: 8 }, option: { minHeight: 52, borderBottomWidth: StyleSheet.hairlineWidth, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, segment: { padding: 4, borderRadius: 12, flexDirection: 'row' }, segmentItem: { flex: 1, minHeight: 38, borderRadius: 9, justifyContent: 'center', alignItems: 'center' }, empty: { minHeight: 220, alignItems: 'center', justifyContent: 'center', padding: 24 }, emptyTitle: { fontWeight: '800', fontSize: 16, marginTop: 10 }, emptyText: { textAlign: 'center', marginTop: 5, fontSize: 13 }, row: { minHeight: 66, flexDirection: 'row', alignItems: 'center', gap: 12, borderBottomWidth: StyleSheet.hairlineWidth, paddingVertical: 9 }, rowIcon: { width: 40, height: 40, borderRadius: 11, alignItems: 'center', justifyContent: 'center' }, rowTitle: { fontSize: 14, fontWeight: '700' }, rowSub: { fontSize: 12, marginTop: 3 } });
