import { useFocusEffect } from '@react-navigation/native';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import React, { useCallback, useEffect, useState } from 'react';
import { Alert, StyleSheet, Text, View } from 'react-native';
import { Button, Card, EmptyState, LoadingView, PageHeader, Pill, Row, Screen, Segmented, SelectField } from '../components/UI';
import { useTheme } from '../contexts/ThemeContext';
import { api, ApiError } from '../services/api';
import type { SchoolClass, Teacher } from '../types';

export function ClassesScreen({ navigation }: any) {
  const { colors } = useTheme(); const query = useQuery({ queryKey: ['classes'], queryFn: () => api.get<SchoolClass[]>('/classes') }); useFocusEffect(useCallback(() => { query.refetch(); }, []));
  const remove = (id: string) => Alert.alert('Delete class?', 'Classes with assigned students cannot be deleted.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Delete', style: 'destructive', onPress: async () => { try { await api.delete(`/classes/${id}`); query.refetch(); } catch (e) { Alert.alert('Could not delete', (e as ApiError).message); } } }]);
  return <Screen refreshing={query.isRefetching} onRefresh={query.refetch}><PageHeader title="Classes" subtitle={`${query.data?.length || 0} active classes`} action={<Button compact title="Create" icon="add" onPress={() => navigation.navigate('ClassForm')} />} />{query.isLoading ? <LoadingView /> : !query.data?.length ? <EmptyState icon="library-outline" title="No classes yet" /> : query.data.map(c => <Card key={c.id}><View style={s.top}><View style={{ flex: 1 }}><Text style={[s.className, { color: colors.text }]}>{c.name || `Grade ${c.grade} ${c.medium} ${c.gender_type}`}</Text><Text style={{ color: colors.muted, fontSize: 12, marginTop: 5 }}>Grade {c.grade} · {c.medium}</Text></View><Pill text={c.gender_type} tone="blue" /></View><View style={s.details}><Text style={{ color: colors.muted, fontSize: 12 }}>{c.total_students || 0} students</Text><Text style={{ color: colors.muted, fontSize: 12 }}>{c.teacher_name || 'Teacher unassigned'}</Text></View><View style={s.buttons}><View style={{ flex: 1 }}><Button compact title="Edit" variant="outline" icon="create-outline" onPress={() => navigation.navigate('ClassForm', { id: c.id })} /></View><Button compact title="" variant="danger" icon="trash-outline" onPress={() => remove(c.id)} /></View></Card>)}</Screen>;
}

export function ClassFormScreen({ route, navigation }: any) {
  const id = route.params?.id as string | undefined; const qc = useQueryClient(); const [form, setForm] = useState({ grade: '', medium: '', genderType: '', teacherId: '' }); const [busy, setBusy] = useState(false);
  const classes = useQuery({ queryKey: ['classes'], queryFn: () => api.get<SchoolClass[]>('/classes') }); const teachers = useQuery({ queryKey: ['teachers'], queryFn: () => api.get<Teacher[]>('/teachers') });
  useEffect(() => { if (id && classes.data) { const c = classes.data.find(x => x.id === id); if (c) setForm({ grade: String(c.grade), medium: c.medium, genderType: c.gender_type, teacherId: c.teacher_id || '' }); } }, [id, classes.data]);
  const save = async () => { if (!form.grade || !form.medium || !form.genderType) return Alert.alert('Check the form', 'Grade, medium, and gender type are required.'); const conflict = classes.data?.some(c => c.id !== id && String(c.grade) === form.grade && c.medium === form.medium && ((form.genderType === 'Mixed' && c.gender_type !== 'Mixed') || (form.genderType !== 'Mixed' && c.gender_type === 'Mixed'))); if (conflict) return Alert.alert('Class conflict', 'A mixed class cannot coexist with separate boys/girls classes for the same grade and medium.'); setBusy(true); try { const payload = { grade: Number(form.grade), medium: form.medium, gender_type: form.genderType, teacher_id: form.teacherId || null }; id ? await api.patch(`/classes/${id}`, payload) : await api.post('/classes', payload); await qc.invalidateQueries({ queryKey: ['classes'] }); navigation.goBack(); } catch (e) { Alert.alert('Could not save class', (e as ApiError).message); } finally { setBusy(false); } };
  return <Screen><PageHeader title={id ? 'Edit Class' : 'Create Class'} subtitle="Class structure and teacher assignment" /><Card style={{ gap: 16 }}><SelectField label="Grade *" value={form.grade} options={Array.from({ length: 11 }, (_, i) => ({ value: String(i + 1), label: `Grade ${i + 1}` }))} onChange={grade => setForm(v => ({ ...v, grade }))} /><SelectField label="Medium *" value={form.medium} options={[{ value: 'Sinhala', label: 'Sinhala' }, { value: 'Tamil', label: 'Tamil' }]} onChange={medium => setForm(v => ({ ...v, medium }))} /><Segmented value={form.genderType} options={[{ value: 'Mixed', label: 'Mixed' }, { value: 'Boys', label: 'Boys' }, { value: 'Girls', label: 'Girls' }]} onChange={genderType => setForm(v => ({ ...v, genderType }))} /><SelectField label="Assigned teacher" value={form.teacherId} options={[{ value: '', label: 'Unassigned' }, ...(teachers.data || []).map(t => ({ value: t.id, label: t.full_name }))]} onChange={teacherId => setForm(v => ({ ...v, teacherId }))} /></Card><Button title={id ? 'Save Changes' : 'Create Class'} icon="save-outline" loading={busy} onPress={save} /></Screen>;
}
const s = StyleSheet.create({ top: { flexDirection: 'row', alignItems: 'flex-start', gap: 10 }, className: { fontWeight: '900', fontSize: 16 }, details: { gap: 6, marginTop: 14 }, buttons: { flexDirection: 'row', gap: 8, marginTop: 16 } });
