import { Ionicons } from '@expo/vector-icons';
import React, { useState } from 'react';
import { Alert, Image, KeyboardAvoidingView, Platform, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Button, Field } from '../components/UI';
import { useAuth } from '../contexts/AuthContext';
import { useTheme } from '../contexts/ThemeContext';

export function LoginScreen() {
  const { colors, dark } = useTheme(); const { login } = useAuth(); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [secure, setSecure] = useState(true); const [busy, setBusy] = useState(false);
  const submit = async () => { if (!email.trim() || !password) return Alert.alert('Missing details', 'Enter your email and password.'); setBusy(true); try { await login(email.trim(), password); } catch (e: any) { Alert.alert('Sign in failed', e?.message || 'Please try again.'); } finally { setBusy(false); } };
  return <SafeAreaView style={{ flex: 1, backgroundColor: colors.background }}><KeyboardAvoidingView style={{ flex: 1 }} behavior="padding"><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={s.page}><View style={s.brand}><Image source={dark ? require('../../assets/ahadiya-logo-white-v3.png') : require('../../assets/ahadiya-logo-black-v3.png')} style={s.logo} resizeMode="contain" /><Text style={[s.school, { color: colors.text }]}>Al-Meera Ahadiya School</Text><Text style={[s.system, { color: colors.primary }]}>Ahadiya Management System</Text></View><View style={[s.panel, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[s.welcome, { color: colors.text }]}>Welcome back</Text><Text style={[s.help, { color: colors.muted }]}>Sign in to manage your school</Text><Field label="Email" placeholder="Enter email" autoCapitalize="none" keyboardType="email-address" value={email} onChangeText={setEmail} /><View><Field label="Password" placeholder="Enter password" secureTextEntry={secure} value={password} onChangeText={setPassword} onSubmitEditing={submit} returnKeyType="done" /><Ionicons onPress={() => setSecure(v => !v)} name={secure ? 'eye-outline' : 'eye-off-outline'} color={colors.muted} size={20} style={s.eye} /></View><Button title="Sign In" icon="log-in-outline" onPress={submit} loading={busy} /></View><Text style={[s.footer, { color: colors.muted }]}>Secure access for authorized staff</Text></ScrollView></KeyboardAvoidingView></SafeAreaView>;
}
const s = StyleSheet.create({ page: { flexGrow: 1, justifyContent: 'center', padding: 22, gap: 28 }, brand: { alignItems: 'center' }, logo: { width: 180, height: 180, marginBottom: 10 }, school: { fontSize: 24, fontWeight: '900', textAlign: 'center' }, system: { fontSize: 14, fontWeight: '700', marginTop: 5 }, panel: { borderWidth: 1, borderRadius: 20, padding: 20, gap: 17 }, welcome: { fontSize: 21, fontWeight: '800' }, help: { fontSize: 13, marginTop: -12 }, eye: { position: 'absolute', right: 14, bottom: 14 }, footer: { textAlign: 'center', fontSize: 12 } });
